### PR TITLE
Fix tmp volume bug and add test for it.

### LINKED ISSUE #63: Clean up tmp volumes
when we are using the write_cnt functions, if it crashes, the tmps volume is not removed.

Image

### PR DESCRIPTION
**Pull request by vladimirobucina**
## Summary
Fix bug with not removing temporary volumes during writing of the table.

## Changes Made
- Update `write_table_volume()` function

## Related Issues
- Fixes #63 

## Testing
- Unit test written to check removal of `tmp` volumes

## Checklist
- [x] Code changes have been tested
- [x] Documentation has been updated, if applicable
- [x] All automated tests pass
- [x] Coding style and naming conventions have been followed
- [x] The PR is ready for review and merge

### CODE REVIEW

File: tests/testthat/test-table-utils.R [hunk 1]
```diff
@@ -240,3 +240,28 @@ test_that("read and write empty table works", {
 
   expect_equal(empty_table, empty_result)
 })
+
+test_that("tmp volume removal works", {
+  # Bad data input to break the test
+  x = list("1", "2", "3")
```
Comment (Cervangirard) [inline tests/testthat/test-table-utils.R:246]: easy fix to quick the ci green :) pleasseee ^^
