### PR TITLE
Fix reading empty tables.

### LINKED ISSUE #73: [BUG] read_cnt for tables fails when 0 results (check write_cnt as well)
### Description
When a user tries to read empty table they don't get proper error message, instead `arrow` package fails because it doesn't have anything to stream.

### Reproducible Example
```
cnt <- connector_databricks_table(
      http_path = http_path_local,
      catalog = catalog_local,
      schema = schema_local
    )

empty_table <- df <- data.frame(Date=as.Date(character()),
                 File=character(), 
                 User=character(), 
                 stringsAsFactors=FALSE) 

cnt$write_cnt(x = empty_table,
                         name = "empty_table")

cnt$read_cnt("empty_table")

```
### Expected Behavior
User should be able to write/read empty table. When reading they should get an empty data.frame.

### Actual Behavior
User gets error:
```
Error: file must be a "InputStream"
```

### Environment
- R Version: 4.5.1
- Package Version: 0.0.5.9000
- Operating System: All

### Impact
This is not something that would happen that often, but needs to be resolved, especially if we have automated set up script.

### Related Issues
/

### PR DESCRIPTION
**Pull request by vladimirobucina**
## Summary
Update `read_table_timepoint` function to return an empty dataframe if there are no records in the table.

## Changes Made
- Using `DBI::dbGetQuery()` function because currently it's not possible to do this in a nice way using brickster.

## Related Issues
- Fixes #73 

## Testing
- Unit test for use case when an empty data frame is written/read

## Checklist
- [x] Code changes have been tested
- [x] Documentation has been updated, if applicable
- [x] All automated tests pass
- [x] Coding style and naming conventions have been followed
- [x] The PR is ready for review and merge

### CODE REVIEW

File: R/table_utils.R [hunk 1]
```diff
@@ -195,6 +195,11 @@ read_table_timepoint <- function(
     format = "ARROW_STREAM"
   )
 
+  if (query_result$manifest$total_chunk_count == 0) {
+    return(DBI::dbGetQuery(connector_object$conn, sql_statement))
+    zephyr::msg_success("Table read successfully!")
```
Comment (Cervangirard) [inline R/table_utils.R:200]: small comment, but because the return is before the message, we will never receive the message ^^
